auth:
  auth_timeout: 30
  auto_request_auth: true
  cloud_url: ''
  token_timeout: 300
cameras:
- connection_type: onvif
  device_class: direct_connect
  ip: 172.28.234.22
  name: ZCY121
  password: ''
  pkdk: ''
  port: 80
  rtsp_path: /stream1
  rtsp_port: 554
  rtsp_sub_path: /stream2
  sn_code: ''
  username: admin
