cameras:
- name: discovered_172_28_234_127
  connection_type: onvif
  ip: 172.28.234.127
  port: 2000
  username: admin
  password: ''
  rtsp_port: 554
  rtsp_path: /md0_0
  rtsp_sub_path: /stream2
  device_model: skyworth
  product_version: mstar
- name: discovered_172_28_234_151
  connection_type: onvif
  ip: 172.28.234.151
  port: 2000
  username: admin
  password: ''
  rtsp_port: 554
  rtsp_path: /md0_0
  rtsp_sub_path: /stream2
  device_model: skyworth
  product_version: mstar
- name: discovered_172_28_234_22
  connection_type: onvif
  ip: 172.28.234.22
  port: 2000
  username: admin
  password: ''
  rtsp_port: 554
  rtsp_path: /md0_0
  rtsp_sub_path: /stream2
  device_model: skyworth
  product_version: mstar
llm:
  backend: local
  model_path: D:\OllamaModels\qwen2.5-0.5b-instruct-q4_k_m.gguf
  base_url: http://localhost:11434
  model: qwen2.5:0.5b
  timeout: 60
  temperature: 0.3
